Our Python implementation can be run in two different ways:

1. Simply use our wrapper script - run.sh and pass it the parameters in order
		- <Bing account key> in quotes
		- Desired Precision
		- Query in quotes
Example : ./run.sh "MWQrrA8YW+6ciAUTJh56VHz1vi/Mdqu0lSbzms3N7NY=" 0.9 "Snow Leopard"

The Bing account key may be found in our README.txt file or you may use
your own.

2. Use python directly. Call python UI.py with the same parameters as above
Example: python UI.py "MWQrrA8YW+6ciAUTJh56VHz1vi/Mdqu0lSbzms3N7NY=" 0.9 "Snow Leopard"
